_wandb:
    value:
        cli_version: 0.28.0
        e:
            067npj26k11wl8ef65ad2svx6ofdv322:
                args:
                    - --num-rollout-steps
                    - "50"
                    - --eval-interval
                    - "10"
                    - --log-rollouts-interval
                    - "10"
                cpu_count: 64
                cpu_count_logical: 128
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "1465680920576"
                        used: "1168428351488"
                email: menghantin@gmail.com
                executable: /home/mt1068@students.ad.unt.edu/assignment5-alignment/.venv/bin/python3
                git:
                    commit: 34e469f6a3d838f45b1b1c1dbedfeb4415dd0c61
                    remote: git@github.com:during-gt/assignment5-alignment.git
                gpu: NVIDIA H100 NVL
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "100485038080"
                      name: NVIDIA H100 NVL
                      uuid: GPU-685d8fc7-5dd0-2a8e-bee8-6cbbb5f85bc5
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "100485038080"
                      name: NVIDIA H100 NVL
                      uuid: GPU-ab59e77a-87e7-1913-bb2f-460b5284e7cd
                host: ci-l-94cl144
                memory:
                    total: "269908914176"
                os: Linux-6.8.0-111-generic-x86_64-with-glibc2.39
                program: -m cs336_alignment.grpo_training
                python: CPython 3.12.3
                root: /home/mt1068@students.ad.unt.edu/assignment5-alignment
                startedAt: "2026-06-29T03:28:19.939240Z"
                writerId: 067npj26k11wl8ef65ad2svx6ofdv322
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 71
            "2":
                - 1
                - 11
                - 41
                - 49
                - 71
            "3":
                - 16
                - 61
            "4": 3.12.3
            "5": 0.28.0
            "6": 5.7.0
            "12": 0.28.0
            "13": linux-x86_64
advantage_eps:
    value: 1e-06
advantage_normalizer:
    value: std
baseline:
    value: mean
device:
    value: cuda:0
eval_batch_size:
    value: 64
eval_interval:
    value: 10
gradient_accumulation_steps:
    value: 32
group_size:
    value: 8
include_stop_str_in_output:
    value: true
learning_rate:
    value: 1e-05
log_rollouts_interval:
    value: 10
loss_normalization:
    value: sequence
max_grad_norm:
    value: 1
max_tokens:
    value: 512
model_name:
    value: allenai/OLMo-2-0425-1B
n_val_examples:
    value: 1024
num_rollout_steps:
    value: 50
rollout_batch_size:
    value: 256
seed:
    value: 42
stop:
    value:
        - </answer>
temperature:
    value: 1
top_p:
    value: 1
